### ISSUE TITLE
[Question] Using with hyprlock or swaylock, different timeout when hyprlock or swaylock is activated

### ISSUE THREAD

**Issue by omnigenous** [hyprwm/hypridle#16]
Is it possible with hypridle to have multiple conditional timeouts?
I want to have one timeout for when hyprlock or swaylock **_not_** running. And other for when hyprlock or swaylock **_is_** running.

Example:

1. hyprlock is not running/active, timeout = 600 seconds
2. hyprlock is running/active, timeout = 60 seconds

Related: https://github.com/swaywm/swayidle/issues/159

**Comment by asiantuntija** [comment]
Can't you do just `pgrep hyprlock && command`?

**Comment by alba4k** [comment]
I think this can be closed? @omnigenous

**Comment by KAGEYAM4** [comment]
> Can't you do just `pgrep hyprlock && command`?

The problem with this is that, lets say 60sec is for screen turn off if hyprlock active, and 100 sec is for screen lock. Now hypridle runs a single timer and executes timeout_action based whin idle timeout reaches that listener. Because 60sec idle timeout comes first, it executed its timeout_action - which will won't turn off the screen. Now idle timeout reaches 100sec and it will lock the screen. And now there are no listener, idle timer keeps on running but it won't reset to 0 unless mouse or key press is done. So 60sec timeout_action won't be executed again untlit hypridle resets.

**Comment by omnigenous** [comment]
Solved, thank you :heart: 

```
listener {
  timeout = 600
  on-timeout = pgrep hyprlockORswaylock || hyprlockORswaylock
}
listener {
  timeout = 660
  on-timeout = pgrep hyprlockORswaylock && command1
  on-resume = command2
}
# If no longer idle but still haven't unlocked
listener {
  timeout = 60
  on-timeout = pgrep hyprlockORswaylock && command1
  on-resume = command2
}
```
