### ISSUE TITLE
/bin/sh: line 1: systemctl suspend: command not found

### ISSUE THREAD

**Issue by dxwil** [hyprwm/hypridle#51]
All in the title, I don't know why hypridle calls the sh shell, but I can't get in to run systemctl. Swaylock, which is at /usr/local/bin, runs for example.

**Comment by vaxerski** [comment]
you can run `/bin/bash -c "cmd"` if the shell matters. What's the problem?

**Comment by vaxerski** [comment]
how are you running hypridle? Sounds like PATH being kinda bork. If you use a login manager, and launch hypridle with `exec-once`,  your .bashrc is not sourced.

**Comment by dxwil** [comment]
If I include the full path of systemctl, I get this
`/bin/bash: line 1: /usr/bin/systemctl suspend: No such file or directory`

**Comment by Silveere** [comment]
i think the issue is that you are quoting the command in your hypridle config. hyprlang doesn't use quotes as far as i know, so it seems to just be passing them to your shell instead. the error messages you're getting are exactly what you get if you try to do the same thing in bash.

![image](https://github.com/hyprwm/hypridle/assets/15041225/b8babaeb-3707-4ea9-9797-62c1d37b4278)

change it to `lock_cmd = systemctl suspend` (without any quoting) and it should work.

**Comment by dxwil** [comment]
That's it!! Thank you, I don't know how I didn't think of that :)

**Comment by vaxerski** [comment]
oh yeah I am blind
