### ISSUE TITLE
I would want to run a command upon unlock

### ISSUE THREAD

**Issue by se7en-x230** [hyprwm/hypridle#56]
Hyperland-git 
Arch

I can't get a command to run not even notify-send upon unlock.
Can someone push me in the right directions please?

**Comment by yawor** [comment]
I don't think hypridle is the right place for this. It doesn't even know that you've successfully unlocked the lock screen. The `unlock_cmd` configuration option is for unlocking from `loginctl` command.
I think this should rather be something that your lock screen does. I've checked hyprlock and it doesn't have such option. Maybe you could do it using a script, which would first execute hyprlock and wait for it to exit, and then do whatever you want after the hyprlock exits. Then in `lock_cmd` use the script instead of executing hyprlock directly.
