### ISSUE TITLE
[BUG] systemd-inhibit not work

### ISSUE THREAD

**Issue by The-Lost-Light** [hyprwm/hypridle#81]
I try `systemd-inhibit --what=idle --mode=block sleep infinity`
and It seems that hypridle is not affected in any way

**Comment by nydragon** [comment]
I second that, works with swayidle but not hypridle. With `ignore_systemd_inhibit = false`

**Comment by ahuston-0** [comment]
So I just checked (because i'm looking to do something similar). `ignore_systemd_inhibit` is on [main](https://github.com/hyprwm/hypridle/blob/cc23f97836adbba1abc8edd48169fb1f1f698c32/src/config/ConfigManager.cpp#L29) but not in the [0.1.2](https://github.com/hyprwm/hypridle/blob/7cff4581a3753154fc5b41f39a098fad49b777b1/src/config/ConfigManager.cpp#L31). So I guess we have to either run off of main or wait for the next release to be cut.
